// §13.9: maschinell vorentworfen — muttersprachliche Prüfung siehe /docs/translation-review.md
import type { LocaleTemplates } from './types';

export const de: LocaleTemplates = {
  openingByType: {
    villa: [
      'Eine in sich ruhende Villa, entworfen um Privatheit, Licht und weite Blickachsen.',
      'Diese Villa behauptet ihren Platz leise, mit Proportionen, die keiner Vorstellung bedürfen.',
      'Eine private Villa von gereifter Architektur und zurückhaltend kuratierten Interieurs.',
      'Eine Villa für ein Leben ohne Eile, abgeschirmt von jeder Nachbarschaft.',
      'Eine Villa, deren Wert in dem liegt, was sie fernhält: Lärm, Einblicke, Kompromisse.',
    ],
    estate: [
      'Ein Anwesen von echtem Zuschnitt, hinter Toren in einer Hand gehalten.',
      'Ein gewachsenes Anwesen, dessen Ländereien über Generationen zusammengeführt wurden.',
      'Ein Generationenanwesen, bei dem das Land Teil der Substanz ist, nicht der Kulisse.',
      'Dieses Anwesen verbindet ernstzunehmende Flächen mit einem Haupthaus von echter Präsenz.',
    ],
    penthouse: [
      'Ein Penthouse über die gesamte oberste Etage, die Stadt auf Distanz gehalten.',
      'Dieses Penthouse lebt von Licht, Höhe und absoluter Diskretion.',
      'Ein Penthouse auf einer Ebene mit den Proportionen eines Hauses — und niemandem darüber.',
      'Ein Penthouse mit privatem Aufzug, angelegt für das Empfangen in der Höhe.',
    ],
    chalet: [
      'Ein Chalet von stiller Autorität, in Holz und Stein für das ganze Jahr gebaut.',
      'Dieses Chalet antwortet dem Berg mit Gewicht: Altholz, tiefe Dachüberstände, präzise Technik.',
      'Ein Chalet über großzügige Ebenen, die Pisten nah und der Trubel fern.',
      'Ein privates Chalet, in dem alpines Handwerk auf zeitgemäßen Komfort trifft.',
    ],
    palazzo: [
      'Ein Palazzo mit dokumentierter Geschichte, restauriert ohne Theatralik.',
      'Dieser Palazzo trägt seine Jahrhunderte leicht: freskierte Decken über moderner Haustechnik.',
      'Ein Palazzo, dessen Räume für das Empfangen entworfen wurden — und es bis heute leisten.',
      'Ein Palazzo, seit seiner Erbauung in wenigen Händen, nun diskret angeboten.',
    ],
    castle: [
      'Ein Schloss in echtem Erhaltungszustand, mit Gut, Nebengebäuden und Geschichte intakt.',
      'Dieses Schloss wurde auf heutigen Standard gebracht, ohne seinen Charakter preiszugeben.',
      'Ein befestigtes Haus von echtem Alter, bewohnbar zu jeder Jahreszeit.',
    ],
    vineyard_estate: [
      'Ein Weingut in Produktion, verkauft mit Reben, Keller und Namen.',
      'Dieses Weingut verbindet ein ernstzunehmendes Wohnhaus mit Land, das sich selbst trägt.',
      'Ein Weingut, bei dem Aussicht, Etikett und Adresse ein und dasselbe sind.',
    ],
    equestrian_estate: [
      'Ein Reitanwesen auf professionellem Standard, von den Stallungen bis zum Dressurviereck.',
      'Dieses Anwesen stellt die Pferde an die erste Stelle, ohne dem Haus Kompromisse abzuverlangen.',
      'Ein arbeitendes Reitanwesen mit Koppeln, Personalwohnungen und Raum zum Wachsen.',
    ],
    townhouse: [
      'Ein Stadthaus in einer der stillen Straßen, die das Viertel ausmachen.',
      'Dieses Stadthaus bietet vertikale Privatheit inmitten von allem.',
      'Ein Stadthaus, Etage für Etage nach strengem Maßstab restauriert.',
    ],
    apartment: [
      'Eine Wohnung auf einer Ebene von ungewöhnlichem Zuschnitt, in einem Haus mit wenigen Einheiten.',
      'Diese Wohnung verbindet Hotelservice mit der Diskretion einer privaten Adresse.',
      'Eine Wohnung auf einem einzigen Niveau; Personal und Sicherheit übernimmt das Haus.',
    ],
    lodge: [
      'Eine Lodge, für die Landschaft platziert und aus den Materialien ihres Ortes gebaut.',
      'Diese Lodge bietet Abgeschiedenheit ohne Askese: voller Service, keine Nachbarn.',
      'Eine private Lodge, gedacht für lange Aufenthalte, Gäste und offenes Land.',
    ],
    ranch: [
      'Eine Ranch von echter Betriebsgröße, verkauft mit Scheunen, Weiden und Wasserrechten.',
      'Diese Ranch verbindet ein komfortables Haupthaus mit Land, das sich in Horizonten misst.',
      'Eine Familienranch in einer Hand, im Ganzen angeboten.',
    ],
    private_island: [
      'Eine ganze Privatinsel in einer Hand, vollständig angeboten.',
      'Ein Inselanwesen, das die letzte Frage der Privatheit endgültig beantwortet.',
      'Diese Privatinsel ist autark: Energie, Wasser, Personalquartiere und eine eigene Ankunft.',
    ],
    _: [
      'Eine Immobilie von seltener Qualität, mit Diskretion angeboten.',
      'Ein Besitz, vollständig um Privatheit und Beständigkeit organisiert.',
      'Ein Haus für Käufer, die Qualität in Jahrzehnten messen, nicht in Saisons.',
      'Eine der wenigen Adressen dieses Ranges, die den Markt überhaupt erreichen.',
    ],
  },
  positioning: [
    'Sie liegt in geschützter Lage in {locality}.',
    'Die Umgebung ist {locality} von seiner stillsten Seite, abseits der Durchgangswege.',
    'Sie hält eine der etabliertesten Adressen von {locality}.',
    'Das Anwesen liegt hinter gewachsenem Grün an einem privaten Abschnitt von {locality}.',
    'Die Anfahrt durch {locality} lässt nichts vom Zuschnitt hinter dem Tor erahnen.',
  ],
  waterSentence: [
    'Die Ländereien treffen mit {frontage} m privater Uferfront auf den {waterBody}.',
    'Es sind {frontage} Meter eigenes Ufer am {waterBody} — {beachType}, vollständig privat.',
    'Die {frontage} Meter Uferfront am {waterBody} stehen im Grundbuch, direkt vom Garten erreichbar.',
    'Das {beachType}-Ufer läuft über {frontage} private Meter am {waterBody} entlang.',
  ],
  waterSentenceNoFrontage: [
    'Die Ländereien sind bis an ihre Grenzen privat; gewachsenes Grün schließt jede Sichtachse.',
    'Auf {plotArea} m² Grund bleibt das Haus von jeder öffentlichen Straße unsichtbar.',
    'Das Land ist zuerst auf Privatheit angelegt, das Beste von {locality} auf Armlänge gehalten.',
    'Gärten, Höfe und Terrassen sind so geordnet, dass jeder Hauptraum seinen eigenen Ausblick besitzt.',
  ],
  accommodationSentence: [
    'Innen: {bedrooms} Schlafzimmer und {bathrooms} Bäder auf {builtArea} m² Wohnfläche.',
    'Das Haus bietet {builtArea} m², aufgeteilt in {bedrooms} Schlafzimmer und {bathrooms} Bäder.',
    'Die Wohnfläche beträgt {builtArea} m² — {bedrooms} Schlafzimmer, {bathrooms} Bäder und großzügige Empfangsräume.',
    '{bedrooms} Schlafzimmer und {bathrooms} Bäder verteilen sich auf {builtArea} m², die Hauptsuite im besten Teil des Grundrisses.',
    'Der Innenraum misst {builtArea} m² — {bedrooms} Schlafzimmer, {bathrooms} Bäder, dazu Personalbereiche.',
  ],
  outdoorSentence: [
    'Draußen erweitern {terrace} m² Terrassen den Wohnraum, eingebettet in {plotArea} m² Grund.',
    'Das Grundstück von {plotArea} m² ist in gewachsenen Schichten angelegt, mit {terrace} m² Terrassen.',
    'Ein Garten von {plotArea} m² umgibt das Haus; die Hauptterrasse mit {terrace} m² fängt das Abendlicht.',
    'Terrassen von {terrace} m² tragen die Jahreszeiten hinaus auf das Grundstück von {plotArea} m².',
  ],
  nauticalSentence: [
    'Ein privater Liegeplatz nimmt ein Boot bis {loa} Meter auf, bei {depth} Metern Wassertiefe.',
    'Boote bis {loa} m liegen längsseits in {depth} m Wasser; Service und Winterlager übernimmt {marina}.',
    'Der eigene Liegeplatz akzeptiert {loa} Meter Boot bei {depth} Metern Tiefe.',
  ],
  locationSentence: [
    'Von {locality} aus ist das Beste von {destination} in Minuten erreicht; der Rest bleibt fern.',
    'Die Adresse hält Restaurants, Schulen und den Flughafen von {destination} in bequemer Reichweite.',
    '{destination} zeigt sich hier von seiner privatesten Seite — und {locality} ist der Grund.',
    'Alles, was {destination} besitzenswert macht, ist nah; nichts von dem, was es füllt.',
  ],
  closingByTier: {
    standard: [
      'In die Collection als Ausnahme unterhalb der üblichen Schwelle aufgenommen — allein der Qualität wegen.',
      'Eine seltene Aufnahme auf diesem Niveau, angeboten mit der Diskretion des stilleren Marktes von {destination}.',
      'Eine der wenigen Immobilien zu diesem Preis, die je für {destination} in die Collection aufgenommen wurden.',
    ],
    premium: [
      'Ein gewichtiger Besitz im stärksten Segment des Marktes von {destination}.',
      'Die Art von Adresse in {destination}, die still und selten den Besitzer wechselt.',
      'Ein souveräner Erwerb unter den etablierten Ausnahmeobjekten von {destination}.',
    ],
    trophy: [
      'Eine der wenigen wirklich unersetzlichen Immobilien in {destination}.',
      'Ein Generationenkauf; ein Fixpunkt von {destination} in privater Hand.',
      'Für die kurze Liste der Käufer, für die {destination} genau diese Adresse bedeutet.',
    ],
  },
  titleByType: {
    villa: [
      'Villa mit privatem Park in {locality}',
      'Private Villa in {locality}',
      'Villa von seltener Qualität, {locality}',
    ],
    estate: ['Anwesen hinter Toren in {locality}', 'Generationenanwesen, {locality}'],
    penthouse: ['Penthouse über eine ganze Etage in {locality}', 'Penthouse über {locality}'],
    chalet: ['Privates Chalet in {locality}', 'Chalet von großem Zuschnitt, {locality}'],
    palazzo: ['Historischer Palazzo in {locality}', 'Restaurierter Palazzo, {locality}'],
    castle: ['Schloss mit Gut bei {locality}', 'Historisches Schloss, {locality}'],
    vineyard_estate: ['Weingut in {locality}', 'Weingut mit Wohnhaus, {locality}'],
    equestrian_estate: ['Reitanwesen bei {locality}'],
    townhouse: ['Stadthaus in {locality}', 'Stadthaus in bester Lage, {locality}'],
    apartment: ['Wohnung auf einer Ebene in {locality}', 'Wohnung von großem Zuschnitt, {locality}'],
    lodge: ['Private Lodge in {locality}'],
    ranch: ['Ranch in einer Hand bei {locality}'],
    private_island: ['Privatinsel vor {locality}'],
    _: ['Private Residenz in {locality}', 'Residenz von seltener Qualität, {locality}'],
  },
  words: {
    beachType: { sand: 'Sand', pebble: 'Kies', rock: 'Fels', mixed: 'gemischt', none: 'naturbelassen' },
    access: {
      private_beach: 'einen Privatstrand',
      shared_beach: 'einen Gemeinschaftsstrand',
      direct_shore: 'direkten Uferzugang',
      private_dock: 'einen privaten Steg',
      private_mooring: 'eine private Mooring',
      marina_berth_included: 'einen inkludierten Marina-Liegeplatz',
      boathouse: 'ein Bootshaus',
      slipway: 'eine Slipanlage',
      seawall_quay: 'eine Kaimauer',
      rock_platform: 'eine Felsplattform',
      riparian_access: 'Ufernutzungsrecht',
      whole_island: 'Eigentum an der ganzen Insel',
    },
  },
};
