import type { LocaleTemplates } from './types';

export const en: LocaleTemplates = {
  openingByType: {
    villa: [
      'A composed villa arranged around privacy, light and long views.',
      'This villa holds its ground quietly, with proportions that need no introduction.',
      'A private villa of settled architecture and carefully edited interiors.',
      'A villa built for unhurried living, screened from every neighbour.',
      'A villa whose value lies in what it withholds: noise, overlooking, compromise.',
    ],
    estate: [
      'An estate of genuine scale, held behind gates in single ownership.',
      'An established estate whose grounds have been assembled over generations.',
      'A generational estate where the land is part of the argument, not the backdrop.',
      'This estate pairs serious acreage with a principal house of real presence.',
    ],
    penthouse: [
      'A penthouse occupying the entire upper floor, with the city held at a distance.',
      'This penthouse trades on light, elevation and absolute discretion.',
      'A lateral penthouse with the proportions of a house and no neighbour above.',
      'A penthouse reached by private lift, arranged for entertaining at altitude.',
    ],
    chalet: [
      'A chalet of quiet authority, built in timber and stone for year-round use.',
      'This chalet answers the mountain with weight: old wood, deep eaves, exact engineering.',
      'A chalet arranged over generous floors, with the slopes close and the crowds far.',
      'A private chalet where alpine craft meets contemporary comfort.',
    ],
    palazzo: [
      'A palazzo of documented history, restored without theatricality.',
      'This palazzo carries its centuries lightly: frescoed ceilings above modern services.',
      'A palazzo whose rooms were drawn for receiving, and still are.',
      'A palazzo held by few families since it was built, now offered discreetly.',
    ],
    castle: [
      'A castle in genuine repair, with its estate, outbuildings and history intact.',
      'This castle has been brought to modern standards without surrendering its character.',
      'A fortified house of real age, habitable in every season.',
    ],
    vineyard_estate: [
      'A vineyard estate in production, sold with its vines, cellar and name.',
      'This wine estate pairs a serious residence with land that earns its keep.',
      'A vineyard estate where the view, the label and the address are the same thing.',
    ],
    equestrian_estate: [
      'An equestrian estate built to professional standard, from stables to schooling arena.',
      'This estate puts the horses first without asking the house to compromise.',
      'A working equestrian property with paddocks, staff quarters and room to grow.',
    ],
    townhouse: [
      'A townhouse on one of the quiet streets that define the district.',
      'This townhouse offers vertical privacy in the middle of everything.',
      'A freehold townhouse restored floor by floor to an exacting standard.',
    ],
    apartment: [
      'A lateral apartment of unusual scale in a building of few residences.',
      'This apartment combines hotel-grade services with the discretion of a private address.',
      'An apartment arranged on a single level, with staff and security handled by the building.',
    ],
    lodge: [
      'A lodge positioned for the landscape, built from the materials of its place.',
      'This lodge offers remoteness without austerity: full services, no neighbours.',
      'A private lodge conceived for long stays, house parties and open country.',
    ],
    ranch: [
      'A ranch of working scale, sold with its barns, grazing and water rights.',
      'This ranch pairs a principal residence of comfort with land measured in horizons.',
      'A legacy ranch held in one ownership, offered whole.',
    ],
    private_island: [
      'A whole private island in single ownership, offered complete.',
      'An island estate that answers the last question of privacy definitively.',
      'This private island is self-contained: power, water, staff quarters and its own arrival.',
    ],
    _: [
      'A property of rare quality, offered with discretion.',
      'A holding organised entirely around privacy and permanence.',
      'A home for buyers who measure quality in decades, not seasons.',
      'One of the few addresses of this order to reach the market at all.',
    ],
  },
  positioning: [
    'It stands in a protected position at {locality}.',
    'The setting is {locality} at its quietest, away from the through-roads.',
    'It occupies one of the most established addresses in {locality}.',
    'The property sits behind mature screening on a private stretch of {locality}.',
    'The approach through {locality} gives no hint of the scale behind the gate.',
  ],
  waterSentence: [
    'The grounds meet the {waterBody} with {frontage} m of private frontage.',
    'There are {frontage} metres of owned {waterBody} shoreline here, {beachType} underfoot and completely private.',
    'Its {frontage}-metre frontage on the {waterBody} belongs to the title, reached directly from the garden.',
    'The {beachType} shoreline runs for {frontage} private metres along the {waterBody}.',
  ],
  waterSentenceNoFrontage: [
    'The grounds are private to their boundaries, with mature planting closing every sightline.',
    'Within {plotArea} m² of grounds, the house is invisible from any public road.',
    'The land is arranged for privacy first, with the best of {locality} kept at arm’s length.',
    'Gardens, courtyards and terraces are ordered so that each principal room owns its outlook.',
  ],
  accommodationSentence: [
    'Inside are {bedrooms} bedrooms and {bathrooms} bathrooms across {builtArea} m² of accommodation.',
    'The house offers {builtArea} m² arranged as {bedrooms} bedrooms and {bathrooms} bathrooms.',
    'Accommodation runs to {builtArea} m², with {bedrooms} bedrooms, {bathrooms} bathrooms and generous receiving rooms.',
    '{bedrooms} bedrooms and {bathrooms} bathrooms occupy {builtArea} m², with the principal suite given the best of the plan.',
    'The interior measures {builtArea} m² — {bedrooms} bedrooms, {bathrooms} bathrooms, and staff accommodation besides.',
  ],
  outdoorSentence: [
    'Outside, {terrace} m² of terracing extends the living space within grounds of {plotArea} m².',
    'The plot of {plotArea} m² is landscaped in mature layers, with {terrace} m² of terraces.',
    'Grounds of {plotArea} m² wrap the house, the {terrace} m² main terrace taking the evening light.',
    'Terraces of {terrace} m² carry the seasons outdoors across the {plotArea} m² plot.',
  ],
  nauticalSentence: [
    'A private berth takes a boat of up to {loa} metres, with {depth} metres of depth alongside.',
    'Boats to {loa} m lie alongside in {depth} m of water, with {marina} handling service and wintering.',
    'Its own mooring accepts {loa} metres of boat at {depth} metres of depth.',
  ],
  locationSentence: [
    'From {locality}, the best of {destination} is minutes away; the rest of it stays away.',
    'The address places {destination}’s restaurants, schools and airport within easy reach.',
    '{destination} is at its most private here, and {locality} is the reason.',
    'Everything that makes {destination} worth owning is close; nothing that makes it crowded is.',
  ],
  closingByTier: {
    standard: [
      'Admitted to the Collection as an exception below the usual threshold, on quality alone.',
      'A rare admission at this level, offered with the discretion of {destination}’s quieter market.',
      'One of the few properties at this price ever admitted to the Collection for {destination}.',
    ],
    premium: [
      'A serious holding in the strongest segment of the {destination} market.',
      'The kind of {destination} address that changes hands quietly, and rarely.',
      'A confident acquisition among {destination}’s established trophy properties.',
    ],
    trophy: [
      'Among the few genuinely irreplaceable properties in {destination}.',
      'A generational acquisition; a landmark of {destination} in private hands.',
      'For the shortlist of buyers to whom {destination} means this exact address.',
    ],
  },
  titleByType: {
    villa: [
      'Villa with private grounds at {locality}',
      'Private villa in {locality}',
      'Villa of rare quality, {locality}',
    ],
    estate: ['Gated estate at {locality}', 'Generational estate, {locality}'],
    penthouse: ['Full-floor penthouse in {locality}', 'Penthouse above {locality}'],
    chalet: ['Private chalet in {locality}', 'Chalet of scale, {locality}'],
    palazzo: ['Historic palazzo in {locality}', 'Restored palazzo, {locality}'],
    castle: ['Castle and estate near {locality}', 'Historic castle, {locality}'],
    vineyard_estate: ['Vineyard estate at {locality}', 'Wine estate with residence, {locality}'],
    equestrian_estate: ['Equestrian estate near {locality}'],
    townhouse: ['Freehold townhouse in {locality}', 'Townhouse in {locality}'],
    apartment: ['Lateral apartment in {locality}', 'Apartment of scale, {locality}'],
    lodge: ['Private lodge at {locality}'],
    ranch: ['Ranch in single ownership near {locality}'],
    private_island: ['Private island off {locality}'],
    _: ['Private residence in {locality}', 'Residence of rare quality, {locality}'],
  },
  words: {
    beachType: { sand: 'sand', pebble: 'pebble', rock: 'rock', mixed: 'mixed', none: 'natural' },
    access: {
      private_beach: 'a private beach',
      shared_beach: 'a shared beach',
      direct_shore: 'direct shore access',
      private_dock: 'a private dock',
      private_mooring: 'a private mooring',
      marina_berth_included: 'an included marina berth',
      boathouse: 'a boathouse',
      slipway: 'a slipway',
      seawall_quay: 'a quay wall',
      rock_platform: 'a rock platform',
      riparian_access: 'riparian access',
      whole_island: 'whole-island ownership',
    },
  },
};
