// §13.9: borrador automático pendiente de revisión nativa — ver /docs/translation-review.md
import type { LocaleTemplates } from './types';

export const es: LocaleTemplates = {
  openingByType: {
    villa: [
      'Una villa serena, concebida en torno a la privacidad, la luz y las vistas largas.',
      'Esta villa ocupa su lugar sin alardes, con proporciones que no necesitan presentación.',
      'Una villa privada de arquitectura asentada e interiores compuestos con mesura.',
      'Una villa pensada para una vida sin prisa, resguardada de cualquier vecino.',
      'Una villa cuyo valor está en lo que mantiene lejos: el ruido, las miradas, los compromisos.',
    ],
    estate: [
      'Una finca de verdadera escala, guardada tras sus puertas en propiedad única.',
      'Una finca consolidada, cuyas tierras se han reunido a lo largo de generaciones.',
      'Una finca generacional donde la tierra forma parte de la sustancia, no del decorado.',
      'Esta finca une hectáreas de peso con una residencia principal de auténtica presencia.',
    ],
    penthouse: [
      'Un ático que ocupa toda la última planta, con la ciudad mantenida a distancia.',
      'Este ático vive de la luz, la altura y una discreción absoluta.',
      'Un ático en una sola planta con las proporciones de una casa y nadie encima.',
      'Un ático con ascensor privado, dispuesto para recibir en las alturas.',
    ],
    chalet: [
      'Un chalet de serena autoridad, en madera y piedra, concebido para todo el año.',
      'Este chalet responde a la montaña con solidez: maderas antiguas, aleros profundos, técnica exacta.',
      'Un chalet desplegado en plantas generosas, con las pistas cerca y el bullicio lejos.',
      'Un chalet privado donde la artesanía alpina se encuentra con el confort contemporáneo.',
    ],
    palazzo: [
      'Un palacio de historia documentada, restaurado sin teatralidad.',
      'Este palacio lleva sus siglos con ligereza: techos con frescos sobre instalaciones modernas.',
      'Un palacio cuyos salones se trazaron para recibir, y aún lo hacen.',
      'Un palacio en manos de pocas familias desde su construcción, hoy ofrecido con discreción.',
    ],
    castle: [
      'Un castillo en verdadero estado de conservación, con su finca, dependencias e historia intactas.',
      'Este castillo se ha llevado a estándares actuales sin renunciar a su carácter.',
      'Una casa fortificada de edad auténtica, habitable en cualquier estación.',
    ],
    vineyard_estate: [
      'Una finca vinícola en producción, vendida con sus viñas, su bodega y su nombre.',
      'Esta finca del vino une una residencia seria con una tierra que se sostiene sola.',
      'Una finca vinícola donde la vista, la etiqueta y la dirección son lo mismo.',
    ],
    equestrian_estate: [
      'Una finca ecuestre construida a estándar profesional, de las cuadras a la pista de trabajo.',
      'Esta finca pone a los caballos primero sin pedirle compromisos a la casa.',
      'Una propiedad ecuestre en activo, con paddocks, alojamiento de servicio y margen para crecer.',
    ],
    townhouse: [
      'Una casa señorial en una de las calles tranquilas que definen el barrio.',
      'Esta casa señorial ofrece privacidad vertical en medio de todo.',
      'Una casa señorial restaurada planta a planta con criterio exigente.',
    ],
    apartment: [
      'Un apartamento en una sola planta, de escala inusual, en un edificio de pocas residencias.',
      'Este apartamento combina servicios de hotel con la discreción de una dirección privada.',
      'Un apartamento en un único nivel, con servicio y seguridad a cargo del edificio.',
    ],
    lodge: [
      'Un lodge situado para el paisaje, construido con los materiales de su lugar.',
      'Este lodge ofrece lejanía sin austeridad: servicios completos, ningún vecino.',
      'Un lodge privado concebido para estancias largas, invitados y campo abierto.',
    ],
    ranch: [
      'Un rancho de escala real, vendido con sus graneros, sus pastos y sus derechos de agua.',
      'Este rancho une una residencia principal confortable con una tierra que se mide en horizontes.',
      'Un rancho de familia en propiedad única, ofrecido entero.',
    ],
    private_island: [
      'Una isla privada completa, en propiedad única, ofrecida entera.',
      'Una finca insular que responde de forma definitiva a la última pregunta de la privacidad.',
      'Esta isla privada es autosuficiente: energía, agua, alojamiento de servicio y llegada propia.',
    ],
    _: [
      'Una propiedad de calidad poco común, ofrecida con discreción.',
      'Un patrimonio organizado por entero en torno a la privacidad y la permanencia.',
      'Una casa para quienes miden la calidad en décadas, no en temporadas.',
      'Una de las pocas direcciones de este rango que llegan al mercado.',
    ],
  },
  positioning: [
    'Se alza en una posición protegida de {locality}.',
    'El entorno es {locality} en su versión más serena, lejos de las vías de paso.',
    'Ocupa una de las direcciones más consolidadas de {locality}.',
    'La propiedad se resguarda tras vegetación madura en un tramo privado de {locality}.',
    'La llegada por {locality} no deja adivinar la escala que hay tras la puerta.',
  ],
  waterSentence: [
    'Los terrenos alcanzan el {waterBody} con {frontage} m de frente privado.',
    'Son {frontage} metros de orilla en propiedad sobre el {waterBody}, de {beachType} y totalmente privados.',
    'Su frente de {frontage} metros al {waterBody} consta en el título, con acceso directo desde el jardín.',
    'La orilla de {beachType} recorre {frontage} metros privados a lo largo del {waterBody}.',
  ],
  waterSentenceNoFrontage: [
    'Los terrenos son privados hasta sus linderos, con vegetación madura cerrando cada perspectiva.',
    'En {plotArea} m² de parcela, la casa resulta invisible desde cualquier vía pública.',
    'La tierra está ordenada ante todo para la privacidad, con lo mejor de {locality} a la distancia justa.',
    'Jardines, patios y terrazas se ordenan para que cada salón principal tenga su propia vista.',
  ],
  accommodationSentence: [
    'En el interior, {bedrooms} dormitorios y {bathrooms} baños sobre {builtArea} m².',
    'La casa ofrece {builtArea} m² distribuidos en {bedrooms} dormitorios y {bathrooms} baños.',
    'La superficie construida es de {builtArea} m² — {bedrooms} dormitorios, {bathrooms} baños y generosos salones de recepción.',
    '{bedrooms} dormitorios y {bathrooms} baños ocupan {builtArea} m², con la suite principal en lo mejor de la planta.',
    'El interior mide {builtArea} m² — {bedrooms} dormitorios, {bathrooms} baños, además del alojamiento de servicio.',
  ],
  outdoorSentence: [
    'En el exterior, {terrace} m² de terrazas prolongan el espacio de vida en una parcela de {plotArea} m².',
    'La parcela de {plotArea} m² está ajardinada en capas maduras, con {terrace} m² de terrazas.',
    'Un jardín de {plotArea} m² rodea la casa; la terraza principal de {terrace} m² recoge la luz de la tarde.',
    'Terrazas de {terrace} m² llevan las estaciones al exterior en la parcela de {plotArea} m².',
  ],
  nauticalSentence: [
    'Un amarre privado admite un barco de hasta {loa} metros, con {depth} metros de calado.',
    'Barcos de hasta {loa} m atracan en {depth} m de agua, con {marina} para el servicio y la invernada.',
    'Su propio amarre acepta {loa} metros de eslora en {depth} metros de fondo.',
  ],
  locationSentence: [
    'Desde {locality}, lo mejor de {destination} queda a minutos; el resto se mantiene lejos.',
    'La dirección deja los restaurantes, los colegios y el aeropuerto de {destination} al alcance.',
    '{destination} se muestra aquí en su versión más privada, y {locality} es la razón.',
    'Todo lo que hace que {destination} merezca poseerse está cerca; nada de lo que la llena lo está.',
  ],
  closingByTier: {
    standard: [
      'Admitida en la Colección como excepción por debajo del umbral habitual, solo por su calidad.',
      'Una admisión poco común a este nivel, ofrecida con la discreción del mercado más silencioso de {destination}.',
      'Una de las pocas propiedades a este precio admitidas jamás en la Colección para {destination}.',
    ],
    premium: [
      'Una propiedad de peso en el segmento más sólido del mercado de {destination}.',
      'El tipo de dirección de {destination} que cambia de manos con discreción, y pocas veces.',
      'Una adquisición firme entre las propiedades de excepción consolidadas de {destination}.',
    ],
    trophy: [
      'Entre las pocas propiedades verdaderamente irremplazables de {destination}.',
      'Una adquisición generacional; un referente de {destination} en manos privadas.',
      'Para la breve lista de compradores para quienes {destination} significa exactamente esta dirección.',
    ],
  },
  titleByType: {
    villa: [
      'Villa con parque privado en {locality}',
      'Villa privada en {locality}',
      'Villa de calidad poco común, {locality}',
    ],
    estate: ['Finca tras puertas en {locality}', 'Finca generacional, {locality}'],
    penthouse: ['Ático de planta completa en {locality}', 'Ático sobre {locality}'],
    chalet: ['Chalet privado en {locality}', 'Chalet de gran escala, {locality}'],
    palazzo: ['Palacio histórico en {locality}', 'Palacio restaurado, {locality}'],
    castle: ['Castillo con finca cerca de {locality}', 'Castillo histórico, {locality}'],
    vineyard_estate: ['Finca vinícola en {locality}', 'Finca del vino con residencia, {locality}'],
    equestrian_estate: ['Finca ecuestre cerca de {locality}'],
    townhouse: ['Casa señorial en {locality}', 'Casa urbana en {locality}'],
    apartment: ['Apartamento en una planta en {locality}', 'Apartamento de gran escala, {locality}'],
    lodge: ['Lodge privado en {locality}'],
    ranch: ['Rancho en propiedad única cerca de {locality}'],
    private_island: ['Isla privada frente a {locality}'],
    _: ['Residencia privada en {locality}', 'Residencia de calidad poco común, {locality}'],
  },
  words: {
    beachType: { sand: 'arena', pebble: 'guijarros', rock: 'roca', mixed: 'mixta', none: 'natural' },
    access: {
      private_beach: 'playa privada',
      shared_beach: 'playa compartida',
      direct_shore: 'acceso directo a la orilla',
      private_dock: 'muelle privado',
      private_mooring: 'fondeo privado',
      marina_berth_included: 'amarre incluido en marina',
      boathouse: 'casa-embarcadero',
      slipway: 'rampa de botadura',
      seawall_quay: 'muelle de escollera',
      rock_platform: 'plataforma rocosa',
      riparian_access: 'acceso ribereño',
      whole_island: 'propiedad de la isla completa',
    },
  },
};
