// §13.9 : brouillon machine à relire par un locuteur natif — voir /docs/translation-review.md
import type { LocaleTemplates } from './types';

export const fr: LocaleTemplates = {
  openingByType: {
    villa: [
      'Une villa posée, dessinée autour de l’intimité, de la lumière et des perspectives lointaines.',
      'Cette villa tient son rang sans effort, avec des proportions qui se passent de présentation.',
      'Une villa privée d’architecture aboutie, aux intérieurs composés avec mesure.',
      'Une villa conçue pour une vie sans hâte, à l’abri de tout voisinage.',
      'Une villa dont la valeur tient à ce qu’elle écarte : le bruit, les regards, les compromis.',
    ],
    estate: [
      'Un domaine d’une réelle ampleur, tenu derrière ses grilles en propriété unique.',
      'Un domaine établi, dont les terres ont été réunies au fil des générations.',
      'Un domaine générationnel où la terre fait partie de la substance, pas du décor.',
      'Ce domaine associe des hectares sérieux à une demeure principale de vraie présence.',
    ],
    penthouse: [
      'Un penthouse occupant tout le dernier étage, la ville tenue à distance.',
      'Ce penthouse vit de lumière, de hauteur et d’une discrétion absolue.',
      'Un penthouse de plain-pied aux proportions d’une maison, sans personne au-dessus.',
      'Un penthouse desservi par ascenseur privé, pensé pour recevoir en altitude.',
    ],
    chalet: [
      'Un chalet d’une autorité tranquille, en bois et en pierre, conçu pour toute l’année.',
      'Ce chalet répond à la montagne avec du poids : vieux bois, avant-toits profonds, technique exacte.',
      'Un chalet déployé sur des niveaux généreux, les pistes proches et la foule loin.',
      'Un chalet privé où l’artisanat alpin rejoint le confort contemporain.',
    ],
    palazzo: [
      'Un palazzo à l’histoire documentée, restauré sans théâtralité.',
      'Ce palazzo porte ses siècles avec légèreté : plafonds à fresques au-dessus d’équipements modernes.',
      'Un palazzo dont les salons furent dessinés pour recevoir, et le font encore.',
      'Un palazzo détenu par peu de familles depuis sa construction, offert aujourd’hui avec discrétion.',
    ],
    castle: [
      'Un château en véritable état, avec son domaine, ses dépendances et son histoire intacts.',
      'Ce château a été porté aux standards actuels sans rien céder de son caractère.',
      'Une demeure fortifiée d’âge authentique, habitable en toute saison.',
    ],
    vineyard_estate: [
      'Un domaine viticole en production, vendu avec ses vignes, son chai et son nom.',
      'Ce domaine du vin associe une résidence sérieuse à une terre qui rapporte.',
      'Un domaine viticole où la vue, l’étiquette et l’adresse ne font qu’un.',
    ],
    equestrian_estate: [
      'Un domaine équestre construit au standard professionnel, des écuries au manège.',
      'Ce domaine met les chevaux en premier sans demander de compromis à la maison.',
      'Une propriété équestre en activité, avec paddocks, logements du personnel et réserve de croissance.',
    ],
    townhouse: [
      'Un hôtel particulier dans l’une des rues calmes qui définissent le quartier.',
      'Cet hôtel particulier offre une intimité verticale au cœur de tout.',
      'Un hôtel particulier restauré étage par étage selon un cahier des charges exigeant.',
    ],
    apartment: [
      'Un appartement de plain-pied d’une ampleur inhabituelle, dans un immeuble de quelques résidences.',
      'Cet appartement allie des services d’hôtel à la discrétion d’une adresse privée.',
      'Un appartement sur un seul niveau, personnel et sécurité assurés par l’immeuble.',
    ],
    lodge: [
      'Un lodge placé pour le paysage, construit avec les matériaux de son lieu.',
      'Ce lodge offre l’éloignement sans l’austérité : services complets, aucun voisin.',
      'Un lodge privé conçu pour les longs séjours, les maisonnées et la campagne ouverte.',
    ],
    ranch: [
      'Un ranch d’échelle réelle, vendu avec ses granges, ses pâturages et ses droits d’eau.',
      'Ce ranch associe une résidence principale de confort à une terre qui se mesure en horizons.',
      'Un ranch de famille en propriété unique, offert dans son entier.',
    ],
    private_island: [
      'Une île privée entière, en propriété unique, offerte complète.',
      'Un domaine insulaire qui règle définitivement la dernière question de l’intimité.',
      'Cette île privée est autonome : énergie, eau, logements du personnel et sa propre arrivée.',
    ],
    _: [
      'Une propriété d’une qualité rare, offerte avec discrétion.',
      'Un patrimoine entièrement organisé autour de l’intimité et de la permanence.',
      'Une maison pour ceux qui mesurent la qualité en décennies, non en saisons.',
      'L’une des rares adresses de ce rang à atteindre le marché.',
    ],
  },
  positioning: [
    'Elle occupe une position protégée à {locality}.',
    'Le cadre est {locality} dans sa version la plus paisible, à l’écart du passage.',
    'Elle tient l’une des adresses les plus établies de {locality}.',
    'La propriété se dissimule derrière des plantations matures, sur un tronçon privé de {locality}.',
    'L’arrivée par {locality} ne laisse rien deviner de l’ampleur derrière la grille.',
  ],
  waterSentence: [
    'Les terres rejoignent {waterBody} avec {frontage} m de rive privée.',
    'Ce sont {frontage} mètres de rivage en pleine propriété sur {waterBody}, {beachType} et entièrement privés.',
    'Son linéaire de {frontage} mètres sur {waterBody} figure au titre, accessible directement depuis le jardin.',
    'La rive de {beachType} court sur {frontage} mètres privés le long de {waterBody}.',
  ],
  waterSentenceNoFrontage: [
    'Les terres sont privées jusqu’à leurs limites, des plantations matures fermant chaque perspective.',
    'Dans {plotArea} m² de parc, la maison reste invisible depuis toute voie publique.',
    'Le terrain est ordonné d’abord pour l’intimité, le meilleur de {locality} tenu à bonne distance.',
    'Jardins, cours et terrasses sont composés pour que chaque pièce de réception possède sa vue.',
  ],
  accommodationSentence: [
    'À l’intérieur, {bedrooms} chambres et {bathrooms} salles de bains sur {builtArea} m².',
    'La maison offre {builtArea} m², soit {bedrooms} chambres et {bathrooms} salles de bains.',
    'La surface habitable atteint {builtArea} m² — {bedrooms} chambres, {bathrooms} salles de bains et de généreuses pièces de réception.',
    '{bedrooms} chambres et {bathrooms} salles de bains occupent {builtArea} m², la suite principale tenant le meilleur du plan.',
    'L’intérieur mesure {builtArea} m² — {bedrooms} chambres, {bathrooms} salles de bains, sans compter les logements du personnel.',
  ],
  outdoorSentence: [
    'À l’extérieur, {terrace} m² de terrasses prolongent l’espace de vie dans un parc de {plotArea} m².',
    'Le terrain de {plotArea} m² est paysagé en strates matures, avec {terrace} m² de terrasses.',
    'Un parc de {plotArea} m² entoure la maison ; la terrasse principale de {terrace} m² retient la lumière du soir.',
    'Des terrasses de {terrace} m² portent les saisons au-dehors sur le terrain de {plotArea} m².',
  ],
  nauticalSentence: [
    'Un amarrage privé reçoit un bateau jusqu’à {loa} mètres, par {depth} mètres de fond.',
    'Des bateaux jusqu’à {loa} m s’amarrent dans {depth} m d’eau, {marina} assurant l’entretien et l’hivernage.',
    'Son propre amarrage accepte {loa} mètres de bateau sur {depth} mètres de fond.',
  ],
  locationSentence: [
    'Depuis {locality}, le meilleur de {destination} est à quelques minutes ; le reste demeure à l’écart.',
    'L’adresse place les restaurants, les écoles et l’aéroport de {destination} à portée immédiate.',
    '{destination} se montre ici sous son jour le plus privé, et {locality} en est la raison.',
    'Tout ce qui rend {destination} digne d’être possédée est proche ; rien de ce qui l’encombre ne l’est.',
  ],
  closingByTier: {
    standard: [
      'Admise dans la Collection à titre d’exception sous le seuil habituel, pour sa seule qualité.',
      'Une admission rare à ce niveau, offerte avec la discrétion du marché le plus calme de {destination}.',
      'L’une des rares propriétés à ce prix jamais admises dans la Collection pour {destination}.',
    ],
    premium: [
      'Un bien de poids dans le segment le plus solide du marché de {destination}.',
      'Le genre d’adresse de {destination} qui change de mains discrètement, et rarement.',
      'Une acquisition sûre parmi les propriétés d’exception établies de {destination}.',
    ],
    trophy: [
      'Parmi les rares biens réellement irremplaçables de {destination}.',
      'Une acquisition générationnelle ; un repère de {destination} en mains privées.',
      'Pour la courte liste d’acquéreurs pour qui {destination} signifie exactement cette adresse.',
    ],
  },
  titleByType: {
    villa: [
      'Villa avec parc privé à {locality}',
      'Villa privée à {locality}',
      'Villa d’une qualité rare, {locality}',
    ],
    estate: ['Domaine clos à {locality}', 'Domaine générationnel, {locality}'],
    penthouse: ['Penthouse sur étage entier à {locality}', 'Penthouse au-dessus de {locality}'],
    chalet: ['Chalet privé à {locality}', 'Chalet de grande échelle, {locality}'],
    palazzo: ['Palazzo historique à {locality}', 'Palazzo restauré, {locality}'],
    castle: ['Château et domaine près de {locality}', 'Château historique, {locality}'],
    vineyard_estate: ['Domaine viticole à {locality}', 'Domaine du vin avec résidence, {locality}'],
    equestrian_estate: ['Domaine équestre près de {locality}'],
    townhouse: ['Hôtel particulier à {locality}', 'Maison de ville à {locality}'],
    apartment: ['Appartement de plain-pied à {locality}', 'Appartement de grande échelle, {locality}'],
    lodge: ['Lodge privé à {locality}'],
    ranch: ['Ranch en propriété unique près de {locality}'],
    private_island: ['Île privée au large de {locality}'],
    _: ['Résidence privée à {locality}', 'Résidence d’une qualité rare, {locality}'],
  },
  words: {
    beachType: { sand: 'sable', pebble: 'galets', rock: 'roche', mixed: 'mixte', none: 'naturel' },
    access: {
      private_beach: 'plage privée',
      shared_beach: 'plage partagée',
      direct_shore: 'accès direct à la rive',
      private_dock: 'ponton privé',
      private_mooring: 'mouillage privé',
      marina_berth_included: 'anneau de marina inclus',
      boathouse: 'hangar à bateaux',
      slipway: 'cale de mise à l’eau',
      seawall_quay: 'quai',
      rock_platform: 'plateforme rocheuse',
      riparian_access: 'accès riverain',
      whole_island: 'île entière en propriété',
    },
  },
};
