// §13.9: machine-drafted per la revisione madrelingua — see /docs/translation-review.md
import type { LocaleTemplates } from './types';

export const it: LocaleTemplates = {
  openingByType: {
    villa: [
      'Una villa composta, disegnata attorno a riservatezza, luce e prospettive profonde.',
      'Questa villa occupa il suo posto con discrezione, con proporzioni che non hanno bisogno di presentazioni.',
      'Una villa privata di architettura matura e interni curati con misura.',
      'Una villa pensata per una vita senza fretta, schermata da ogni vicino.',
      'Una villa il cui valore sta in ciò che tiene lontano: rumore, sguardi, compromessi.',
    ],
    estate: [
      'Una tenuta di vera ampiezza, custodita dietro i cancelli in proprietà unica.',
      'Una tenuta consolidata, i cui terreni sono stati riuniti nel corso di generazioni.',
      'Una tenuta generazionale in cui la terra è parte della sostanza, non dello sfondo.',
      'Questa tenuta unisce ettari importanti a una residenza principale di vera presenza.',
    ],
    penthouse: [
      'Un attico che occupa l’intero ultimo piano, con la città tenuta a distanza.',
      'Questo attico vive di luce, altezza e discrezione assoluta.',
      'Un attico su un unico livello con le proporzioni di una casa e nessuno sopra.',
      'Un attico raggiunto da ascensore privato, disegnato per ricevere in quota.',
    ],
    chalet: [
      'Uno chalet di quieta autorevolezza, in legno e pietra, pensato per tutto l’anno.',
      'Questo chalet risponde alla montagna con sostanza: legni antichi, falde profonde, tecnica precisa.',
      'Uno chalet articolato su piani generosi, con le piste vicine e la folla lontana.',
      'Uno chalet privato dove l’artigianato alpino incontra il comfort contemporaneo.',
    ],
    palazzo: [
      'Un palazzo di storia documentata, restaurato senza teatralità.',
      'Questo palazzo porta i suoi secoli con leggerezza: soffitti affrescati sopra impianti moderni.',
      'Un palazzo le cui sale furono disegnate per ricevere, e ancora lo fanno.',
      'Un palazzo appartenuto a poche famiglie dalla sua costruzione, oggi offerto con discrezione.',
    ],
    castle: [
      'Un castello in autentico stato di conservazione, con tenuta, dipendenze e storia intatte.',
      'Questo castello è stato portato a standard moderni senza rinunciare al proprio carattere.',
      'Una dimora fortificata di età autentica, abitabile in ogni stagione.',
    ],
    vineyard_estate: [
      'Una tenuta vitivinicola in produzione, venduta con le vigne, la cantina e il nome.',
      'Questa tenuta del vino unisce una residenza importante a una terra che rende.',
      'Una tenuta vitivinicola in cui la vista, l’etichetta e l’indirizzo coincidono.',
    ],
    equestrian_estate: [
      'Una tenuta equestre costruita a standard professionale, dalle scuderie al campo di lavoro.',
      'Questa tenuta mette i cavalli al primo posto senza chiedere compromessi alla casa.',
      'Una proprietà equestre operativa con paddock, alloggi per il personale e margini di crescita.',
    ],
    townhouse: [
      'Una dimora di città in una delle vie tranquille che definiscono il quartiere.',
      'Questa dimora di città offre riservatezza verticale nel cuore di tutto.',
      'Una dimora di città restaurata piano per piano con criterio rigoroso.',
    ],
    apartment: [
      'Un appartamento su un unico livello, di ampiezza inconsueta, in un edificio di poche residenze.',
      'Questo appartamento unisce servizi da grande albergo alla discrezione di un indirizzo privato.',
      'Un appartamento su un solo piano, con personale e sicurezza gestiti dall’edificio.',
    ],
    lodge: [
      'Un lodge posizionato per il paesaggio, costruito con i materiali del suo luogo.',
      'Questo lodge offre lontananza senza austerità: servizi completi, nessun vicino.',
      'Un lodge privato pensato per soggiorni lunghi, ospiti e campagna aperta.',
    ],
    ranch: [
      'Un ranch di scala operativa, venduto con fienili, pascoli e diritti d’acqua.',
      'Questo ranch unisce una residenza principale confortevole a una terra misurata in orizzonti.',
      'Un ranch di famiglia in proprietà unica, offerto per intero.',
    ],
    private_island: [
      'Un’isola privata intera, in proprietà unica, offerta completa.',
      'Una tenuta insulare che risolve in via definitiva l’ultima domanda sulla riservatezza.',
      'Quest’isola privata è autonoma: energia, acqua, alloggi per il personale e un proprio arrivo.',
    ],
    _: [
      'Una proprietà di rara qualità, offerta con discrezione.',
      'Un patrimonio organizzato interamente attorno a riservatezza e permanenza.',
      'Una casa per chi misura la qualità in decenni, non in stagioni.',
      'Uno dei pochi indirizzi di questo livello a raggiungere il mercato.',
    ],
  },
  positioning: [
    'Sorge in posizione protetta a {locality}.',
    'Il contesto è {locality} nella sua versione più quieta, lontano dalle strade di passaggio.',
    'Occupa uno degli indirizzi più consolidati di {locality}.',
    'La proprietà è riparata da verde maturo in un tratto privato di {locality}.',
    'L’arrivo attraverso {locality} non lascia intuire la scala oltre il cancello.',
  ],
  waterSentence: [
    'I terreni incontrano il {waterBody} con {frontage} m di fronte privato.',
    'Sono {frontage} i metri di riva di proprietà sul {waterBody}, {beachType} e completamente privati.',
    'Il fronte di {frontage} metri sul {waterBody} appartiene al titolo, raggiungibile direttamente dal giardino.',
    'La riva di {beachType} corre per {frontage} metri privati lungo il {waterBody}.',
  ],
  waterSentenceNoFrontage: [
    'I terreni sono privati fino ai confini, con verde maturo a chiudere ogni prospettiva.',
    'Nei {plotArea} m² di parco, la casa resta invisibile da qualsiasi strada pubblica.',
    'La terra è disegnata anzitutto per la riservatezza, con il meglio di {locality} a giusta distanza.',
    'Giardini, corti e terrazze sono ordinati perché ogni sala principale abbia la propria veduta.',
  ],
  accommodationSentence: [
    'All’interno, {bedrooms} camere e {bathrooms} bagni su {builtArea} m² di superficie.',
    'La casa offre {builtArea} m² con {bedrooms} camere e {bathrooms} bagni.',
    'La superficie interna è di {builtArea} m² — {bedrooms} camere, {bathrooms} bagni e generose sale di rappresentanza.',
    '{bedrooms} camere e {bathrooms} bagni occupano {builtArea} m², con la suite principale nella parte migliore della pianta.',
    'L’interno misura {builtArea} m² — {bedrooms} camere, {bathrooms} bagni, oltre agli alloggi per il personale.',
  ],
  outdoorSentence: [
    'All’esterno, {terrace} m² di terrazze prolungano lo spazio abitativo in un parco di {plotArea} m².',
    'Il lotto di {plotArea} m² è disegnato a verdi maturi, con {terrace} m² di terrazze.',
    'Un parco di {plotArea} m² avvolge la casa; la terrazza principale di {terrace} m² raccoglie la luce della sera.',
    'Terrazze per {terrace} m² portano le stagioni all’aperto nel lotto di {plotArea} m².',
  ],
  nauticalSentence: [
    'Un ormeggio privato accoglie una barca fino a {loa} metri, con {depth} metri di fondale.',
    'Barche fino a {loa} m ormeggiano in {depth} m d’acqua, con {marina} per assistenza e rimessaggio.',
    'L’ormeggio di proprietà accetta {loa} metri di barca su {depth} metri di fondale.',
  ],
  locationSentence: [
    'Da {locality}, il meglio di {destination} è a pochi minuti; il resto rimane lontano.',
    'L’indirizzo tiene a portata ristoranti, scuole e aeroporto di {destination}.',
    '{destination} è qui nella sua versione più riservata, e {locality} ne è la ragione.',
    'Tutto ciò che rende {destination} degna di essere posseduta è vicino; nulla di ciò che la affolla lo è.',
  ],
  closingByTier: {
    standard: [
      'Ammessa alla Collezione come eccezione sotto la soglia consueta, per sola qualità.',
      'Un’ammissione rara a questo livello, offerta con la discrezione del mercato più quieto di {destination}.',
      'Una delle poche proprietà a questo prezzo mai ammesse alla Collezione per {destination}.',
    ],
    premium: [
      'Una proprietà di peso nel segmento più forte del mercato di {destination}.',
      'Il tipo di indirizzo di {destination} che cambia proprietario in silenzio, e di rado.',
      'Un acquisto sicuro tra le proprietà trofeo consolidate di {destination}.',
    ],
    trophy: [
      'Tra le poche proprietà davvero irripetibili di {destination}.',
      'Un acquisto generazionale; un punto fermo di {destination} in mani private.',
      'Per la ristretta lista di acquirenti per cui {destination} significa esattamente questo indirizzo.',
    ],
  },
  titleByType: {
    villa: [
      'Villa con parco privato a {locality}',
      'Villa privata a {locality}',
      'Villa di rara qualità, {locality}',
    ],
    estate: ['Tenuta recintata a {locality}', 'Tenuta generazionale, {locality}'],
    penthouse: ['Attico su intero piano a {locality}', 'Attico sopra {locality}'],
    chalet: ['Chalet privato a {locality}', 'Chalet di ampia scala, {locality}'],
    palazzo: ['Palazzo storico a {locality}', 'Palazzo restaurato, {locality}'],
    castle: ['Castello con tenuta presso {locality}', 'Castello storico, {locality}'],
    vineyard_estate: ['Tenuta vitivinicola a {locality}', 'Tenuta del vino con residenza, {locality}'],
    equestrian_estate: ['Tenuta equestre presso {locality}'],
    townhouse: ['Dimora di città a {locality}', 'Palazzetto a {locality}'],
    apartment: ['Appartamento su un livello a {locality}', 'Appartamento di ampia scala, {locality}'],
    lodge: ['Lodge privato a {locality}'],
    ranch: ['Ranch in proprietà unica presso {locality}'],
    private_island: ['Isola privata al largo di {locality}'],
    _: ['Residenza privata a {locality}', 'Residenza di rara qualità, {locality}'],
  },
  words: {
    beachType: { sand: 'sabbia', pebble: 'ciottoli', rock: 'roccia', mixed: 'mista', none: 'naturale' },
    access: {
      private_beach: 'spiaggia privata',
      shared_beach: 'spiaggia condivisa',
      direct_shore: 'accesso diretto alla riva',
      private_dock: 'pontile privato',
      private_mooring: 'ormeggio privato',
      marina_berth_included: 'posto barca incluso in marina',
      boathouse: 'darsena',
      slipway: 'scivolo di alaggio',
      seawall_quay: 'banchina',
      rock_platform: 'piattaforma di roccia',
      riparian_access: 'accesso rivierasco',
      whole_island: 'proprietà dell’intera isola',
    },
  },
};
