/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    media: Media;
    documents: Document;
    properties: Property;
    agencies: Agency;
    agents: Agent;
    markets: Market;
    enquiries: Enquiry;
    'saved-listings': SavedListing;
    requirements: Requirement;
    'member-activity': MemberActivity;
    reports: Report;
    'fx-snapshots': FxSnapshot;
    'segment-pages': SegmentPage;
    'agency-applications': AgencyApplication;
    taxonomies: Taxonomy;
    articles: Article;
    pages: Page;
    redirects: Redirect;
    'audit-logs': AuditLog;
    'import-jobs': ImportJob;
    'consent-records': ConsentRecord;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    agencies: AgenciesSelect<false> | AgenciesSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'saved-listings': SavedListingsSelect<false> | SavedListingsSelect<true>;
    requirements: RequirementsSelect<false> | RequirementsSelect<true>;
    'member-activity': MemberActivitySelect<false> | MemberActivitySelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'fx-snapshots': FxSnapshotsSelect<false> | FxSnapshotsSelect<true>;
    'segment-pages': SegmentPagesSelect<false> | SegmentPagesSelect<true>;
    'agency-applications': AgencyApplicationsSelect<false> | AgencyApplicationsSelect<true>;
    taxonomies: TaxonomiesSelect<false> | TaxonomiesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'import-jobs': ImportJobsSelect<false> | ImportJobsSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru')
    | ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'it' | 'fr' | 'de' | 'es' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'agency_admin' | 'agency_agent';
  /**
   * Required for agency roles. Scopes every query they make.
   */
  agency?: (number | null) | Agency;
  /**
   * Links an agency_agent user to their public agent profile for lead routing and "own listings" scoping.
   */
  agentProfile?: (number | null) | Agent;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies".
 */
export interface Agency {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * ISO-3166-1 alpha-2.
   */
  country?: string | null;
  languages?: ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru')[] | null;
  website?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  licenceNumber?: string | null;
  verified?: boolean | null;
  verifiedAt?: string | null;
  /**
   * verified tier auto-approves listings that pass automated validation (§8.2).
   */
  tier?: ('standard' | 'verified' | 'partner') | null;
  listingQuota?: number | null;
  /**
   * Inbound feed configuration (§8.5). Polled every 6 h.
   */
  feed?: {
    feedUrl?: string | null;
    /**
     * Per-agency ingest token.
     */
    feedToken?: string | null;
    feedFormat?: ('native_json' | 'kyero_xml' | 'resales_online' | 'houzez_wp' | 'generic_csv') | null;
    feedLastRunAt?: string | null;
    feedLastStatus?: string | null;
    /**
     * Source-field → schema mapping for generic feeds (§8.5).
     */
    fieldMapping?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * §6.5: a listing can show 10 public images and hold 30 for members. members = private bucket + signed URLs.
   */
  visibility: 'public' | 'members';
  /**
   * Set automatically for agency uploads. Scopes edit access.
   */
  agency?: (number | null) | Agency;
  credit?: string | null;
  /**
   * Licence position for this asset (§13.2), e.g. "agency-supplied", "Unsplash".
   */
  licence?: string | null;
  sourceUrl?: string | null;
  /**
   * Source-API photo id (§13.2.3) — powers dedupe and purge.
   */
  sourceId?: string | null;
  blurhash?: string | null;
  dominantColor?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    w320?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w640?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w960?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w1280?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w1920?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w2560?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  name: string;
  agency: number | Agency;
  photo?: (number | null) | Media;
  /**
   * e.g. "Senior Partner".
   */
  role?: string | null;
  languages?: ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru')[] | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  receivesLeads?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * End users (the off-market audience) — entirely separate from staff Users. §6.6.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name?: string | null;
  phone?: string | null;
  country?: string | null;
  preferredLocale?: ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru') | null;
  /**
   * Self-declared, optional, never gating (§6.6).
   */
  memberType?: ('buyer' | 'advisor' | 'broker' | 'developer' | 'other') | null;
  /**
   * pending only occurs while MEMBER_REQUIRE_APPROVAL=true (§2.3).
   */
  status: 'active' | 'pending' | 'suspended';
  emailVerifiedAt?: string | null;
  marketingConsent?: boolean | null;
  consentedAt?: string | null;
  consentIp?: string | null;
  lastActiveAt?: string | null;
  source?: ('organic' | 'off_market_cta' | 'report_download' | 'enquiry' | 'referral') | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional TOTP 2FA (§8.5); enrolled via /api/member/totp.
   */
  twoFactorEnabled?: boolean | null;
  totpSecret?: string | null;
  pendingTotpSecret?: string | null;
  /**
   * Reserved for §23 (NDA / capability gating). Never written in Phase 1.
   */
  reserved?: {
    ndaStatus?: string | null;
    ndaSignedAt?: string | null;
    capabilityStatus?: string | null;
    capabilityBand?: string | null;
    tier?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'members';
}
/**
 * Private assets. Never in a sitemap, never cached publicly, never linked directly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  documentType: 'floor_plan' | 'brochure' | 'inventory' | 'survey' | 'report_pdf' | 'other';
  property?: (number | null) | Property;
  /**
   * Set automatically for agency uploads. Scopes edit access.
   */
  agency?: (number | null) | Agency;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Lawrence lists property from €20M (€10–20M only on the prime exception track, an admin decision). Off-market listings never have a slug, never appear in sitemaps, feeds or the public search collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  title: string;
  subtitle?: string | null;
  /**
   * The agency's own listing code. Unique per agency.
   */
  reference?: string | null;
  propertyType:
    | 'villa'
    | 'estate'
    | 'penthouse'
    | 'townhouse'
    | 'chalet'
    | 'castle'
    | 'palazzo'
    | 'private_island'
    | 'vineyard_estate'
    | 'equestrian_estate'
    | 'hotel_resort'
    | 'development_site'
    | 'apartment'
    | 'lodge'
    | 'ranch';
  availableFrom?: string | null;
  priceType: 'fixed' | 'on_request' | 'price_band' | 'auction';
  priceAmount?: number | null;
  currency: 'EUR' | 'USD' | 'GBP' | 'CHF' | 'AED' | 'SGD' | 'HKD';
  priceBandMin?: number | null;
  priceBandMax?: number | null;
  /**
   * Admin-only, never serialised to any audience. Required to publish a listing without an exact public price — the €20M threshold is enforced on it.
   */
  internalValueEur?: number | null;
  tenure?: ('freehold' | 'leasehold' | 'usufruct' | 'concession') | null;
  ownershipStructure?: ('direct' | 'spv' | 'trust' | 'foundation' | 'company') | null;
  saleStructure?: ('asset_sale' | 'share_transfer' | 'fractional' | 'auction') | null;
  /**
   * Members-only extra (§8.3).
   */
  annualRunningCostEur?: number | null;
  /**
   * Factual, sourced — never advice.
   */
  taxNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mandateType?: ('exclusive' | 'open' | 'introduction_only') | null;
  /**
   * Staff-only.
   */
  commissionTerms?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  receptionRooms?: number | null;
  staffAccommodation?: number | null;
  builtAreaSqm?: number | null;
  plotAreaSqm?: number | null;
  plotAreaHa?: number | null;
  terraceAreaSqm?: number | null;
  floors?: number | null;
  yearBuilt?: number | null;
  renovatedYear?: number | null;
  parkingSpaces?: number | null;
  architect?: string | null;
  heritageStatus?: ('none' | 'listed' | 'protected' | 'unesco_area') | null;
  condition?: ('new' | 'renovated' | 'good' | 'to_renovate' | 'shell') | null;
  energyRating?: string | null;
  /**
   * How a €60M estate is narrated — history, architecture, land (§3.2).
   */
  provenance?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | (
        | 'pool'
        | 'indoor_pool'
        | 'spa'
        | 'gym'
        | 'cinema'
        | 'wine_cellar'
        | 'ballroom'
        | 'library'
        | 'chapel'
        | 'helipad'
        | 'tennis'
        | 'padel'
        | 'golf_hole'
        | 'equestrian'
        | 'vineyard'
        | 'olive_grove'
        | 'beach'
        | 'private_dock'
        | 'marina_berth'
        | 'ski_in_ski_out'
        | 'gatehouse'
        | 'staff_quarters'
        | 'guest_houses'
        | 'generator'
        | 'geothermal'
        | 'solar'
        | 'smart_home'
        | 'car_gallery'
        | 'panic_room'
      )[]
    | null;
  /**
   * Optional §6.3 sub-block — valuable at this level, and the bridge to the sister portal.
   */
  waterfront?: {
    waterAccess?: boolean | null;
    waterBodyType?: ('sea' | 'ocean' | 'lake' | 'river' | 'lagoon' | 'canal' | 'fjord' | 'bay' | 'estuary') | null;
    waterFrontageM?: number | null;
    mooringType?:
      ('none' | 'buoy' | 'jetty' | 'pontoon' | 'fixed_dock' | 'floating_dock' | 'boat_lift' | 'marina_berth') | null;
    maxBoatLoaM?: number | null;
    berthCount?: number | null;
  };
  location?: {
    /**
     * Audience-aware display string, e.g. "Cap Ferrat, Côte d'Azur".
     */
    label?: string | null;
    /**
     * Staff-only. Never serialised to any audience.
     */
    addressLine?: string | null;
    locality?: string | null;
    province?: string | null;
    region?: string | null;
    /**
     * ISO-3166-1 alpha-2, e.g. IT, FR, US.
     */
    country?: string | null;
    continent?: string | null;
    /**
     * The Market this listing belongs to (§6.4).
     */
    market?: (number | null) | Market;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
    /**
     * Exact pins only where the seller permits (§4.8). approximate_500m renders a jittered circle publicly; locality_only sends no coordinates at all.
     */
    coordinatePrecision?: ('exact' | 'approximate_500m' | 'locality_only') | null;
    /**
     * The coarsest truthful label shown to anonymous visitors.
     */
    publicGeography?: ('country' | 'region' | 'market' | 'locality') | null;
  };
  /**
   * Ordered. The first image is the hero and card image.
   */
  media?: (number | Media)[] | null;
  videoUrl?: string | null;
  virtualTourUrl?: string | null;
  /**
   * Members-only by default (§6.5), served via signed URLs.
   */
  floorplans?: (number | Document)[] | null;
  /**
   * Private — members via signed URL, staff, owning agency. Never public.
   */
  documents?: (number | Document)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * "How should this property be published?" — the one required control (§8.4). It sets channel and price disclosure.
   */
  publication: 'published_openly' | 'published_without_price' | 'published_as_band' | 'off_market';
  /**
   * Derived from the publication control — the single routing decision.
   */
  channel: 'public' | 'off_market';
  /**
   * Derived for public listings; for off-market listings members see exact or band (§8.3).
   */
  priceDisclosure: 'exact' | 'band' | 'on_request';
  /**
   * trophy/signature derive from the EUR value automatically. prime (€10–20M) is an explicit admin decision, capped at 10% of published inventory.
   */
  valueTier?: ('prime' | 'trophy' | 'signature') | null;
  /**
   * Generated on first publish; always null for off-market listings (addressed by id). Changes create a Redirect.
   */
  slug?: string | null;
  /**
   * Multi-tenancy key. Every query is scoped by it.
   */
  agency: number | Agency;
  /**
   * Enquiry routing target.
   */
  agent?: (number | null) | Agent;
  status: 'draft' | 'available' | 'reserved' | 'under_offer' | 'sold' | 'withdrawn' | 'expired' | 'archived';
  /**
   * Dormant in Phase 1; Track B turns the queue on.
   */
  moderation: 'unreviewed' | 'approved' | 'rejected' | 'changes_requested';
  /**
   * Shown to the submitter. Not public.
   */
  moderationNote?: string | null;
  /**
   * Editorial only. Agencies cannot self-feature.
   */
  featured?: boolean | null;
  /**
   * Demo data: SAMPLE badge, noindex, out of sitemaps.
   */
  isSample?: boolean | null;
  /**
   * Computed from the daily FX snapshot. The only field used for price sorting/filtering.
   */
  priceEur?: number | null;
  priceBandMinEur?: number | null;
  priceBandMaxEur?: number | null;
  publishedAt?: string | null;
  /**
   * publishedAt + 120 days unless availability is reconfirmed (§9.3).
   */
  expiresAt?: string | null;
  /**
   * Set when availability is confirmed still current.
   */
  lastVerifiedAt?: string | null;
  /**
   * When the §9.3 T-14 confirmation email last went out.
   */
  expiryReminderSentAt?: string | null;
  sourceType: 'manual' | 'csv_import' | 'feed' | 'owner_submission';
  /**
   * Set by duplicate detection (§6.1).
   */
  duplicateOf?: (number | null) | Property;
  fingerprint?: string | null;
  viewCount?: number | null;
  /**
   * Off-market views counted separately (§6.1).
   */
  memberViewCount?: number | null;
  enquiryCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: number;
  name: string;
  /**
   * Per-locale slug (§6.7); the §5.5 resolver 301s aliases to the canonical.
   */
  slug: string;
  country?: string | null;
  region?: string | null;
  /**
   * GeoJSON polygon of the market boundary (§6.7). Drawn from OSM/Natural Earth (§13.5).
   */
  polygon?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  centroid?: [number, number] | null;
  heroImage?: (number | null) | Media;
  /**
   * §15.6 answer-first: a 40–60-word direct answer with the key figures, units and dates. Opens the page and the meta description.
   */
  answer?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * §11.5 buying notes — structures, typical costs, timelines. Factual and sourced, never advice.
   */
  buyingNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * §11.5 FAQ rendered with FAQPage JSON-LD. Question-form H2s per §15.6.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * §11.5 related markets for the 6–10 internal links block.
   */
  relatedMarkets?: (number | Market)[] | null;
  /**
   * Editor-maintained market data (§6.7). Every value needs its source URL and as-of date to count toward the §5.5 three-sourced-data-points rule.
   */
  stats?: {
    medianPriceEurPerSqm?: {
      value?: number | null;
      /**
       * Source URL — required for the stat to publish.
       */
      source?: string | null;
      asOfDate?: string | null;
    };
    /**
     * Where prime pricing starts in this market.
     */
    primeEntryEur?: {
      value?: number | null;
      /**
       * Source URL — required for the stat to publish.
       */
      source?: string | null;
      asOfDate?: string | null;
    };
    yoyChangePct?: {
      value?: number | null;
      /**
       * Source URL — required for the stat to publish.
       */
      source?: string | null;
      asOfDate?: string | null;
    };
    avgDaysOnMarket?: {
      value?: number | null;
      /**
       * Source URL — required for the stat to publish.
       */
      source?: string | null;
      asOfDate?: string | null;
    };
    transactionVolumeBand?: {
      /**
       * Transactions per year at this level — banded, never faked precision.
       */
      value?: ('under_10' | '10_50' | '50_200' | 'over_200') | null;
      source?: string | null;
      asOfDate?: string | null;
    };
  };
  /**
   * Demo data: SAMPLE notice, noindex, out of sitemaps.
   */
  isSample?: boolean | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  property?: (number | null) | Property;
  /**
   * Denormalised for routing and access scoping.
   */
  agency?: (number | null) | Agency;
  /**
   * Routing target snapshot (property.agent at submission time).
   */
  agent?: (number | null) | Agent;
  /**
   * Set when the enquirer was authenticated (§6.6).
   */
  member?: (number | null) | Member;
  locale?: ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru') | null;
  source: 'listing' | 'off_market' | 'market_page' | 'report' | 'contact' | 'sell' | 'desk_call';
  status: 'new' | 'sent' | 'viewed' | 'qualified' | 'spam';
  consent?: {
    consentMarketing?: boolean | null;
    consentedAt?: string | null;
    consentIp?: string | null;
  };
  /**
   * When the unanswered-enquiry reminder went out.
   */
  reminderSentAt?: string | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Reserved for the §23 CRM seam.
   */
  crmContactId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-listings".
 */
export interface SavedListing {
  id: number;
  member: number | Member;
  property: number | Property;
  /**
   * Private to the member. Never shown to agencies or in analytics.
   */
  note?: string | null;
  savedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requirements".
 */
export interface Requirement {
  id: number;
  member: number | Member;
  budgetMinEur?: number | null;
  budgetMaxEur?: number | null;
  currency?: ('EUR' | 'USD' | 'GBP' | 'CHF' | 'AED' | 'SGD' | 'HKD') | null;
  markets?: (number | Market)[] | null;
  propertyTypes?:
    | (
        | 'villa'
        | 'estate'
        | 'penthouse'
        | 'townhouse'
        | 'chalet'
        | 'castle'
        | 'palazzo'
        | 'private_island'
        | 'vineyard_estate'
        | 'equestrian_estate'
        | 'hotel_resort'
        | 'development_site'
        | 'apartment'
        | 'lodge'
        | 'ranch'
      )[]
    | null;
  mustHaveFeatures?:
    | (
        | 'pool'
        | 'indoor_pool'
        | 'spa'
        | 'gym'
        | 'cinema'
        | 'wine_cellar'
        | 'ballroom'
        | 'library'
        | 'chapel'
        | 'helipad'
        | 'tennis'
        | 'padel'
        | 'golf_hole'
        | 'equestrian'
        | 'vineyard'
        | 'olive_grove'
        | 'beach'
        | 'private_dock'
        | 'marina_berth'
        | 'ski_in_ski_out'
        | 'gatehouse'
        | 'staff_quarters'
        | 'guest_houses'
        | 'generator'
        | 'geothermal'
        | 'solar'
        | 'smart_home'
        | 'car_gallery'
        | 'panic_room'
      )[]
    | null;
  timeline?: ('immediate' | '6_months' | '12_months' | 'opportunistic') | null;
  notes?: string | null;
  status: 'active' | 'paused' | 'closed';
  notifyByEmail?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-activity".
 */
export interface MemberActivity {
  id: number;
  member: number | Member;
  property?: (number | null) | Property;
  action: 'off_market_list' | 'off_market_view' | 'document_download' | 'saved' | 'enquiry';
  at: string;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  title: string;
  slug: string;
  /**
   * Ungated, 400–600 words with the key findings and figures (§11.6). Public and indexable.
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Gated full report — requires an account, served via signed URL (§6.5).
   */
  pdf?: (number | null) | Document;
  /**
   * Chart data for the summary page (§6.7); every series carries its source.
   */
  charts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publicationDate: string;
  authors?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Cross-links to the relevant market pages (§11.5).
   */
  markets?: (number | Market)[] | null;
  /**
   * Demo data: SAMPLE notice, noindex, out of sitemaps.
   */
  isSample?: boolean | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fx-snapshots".
 */
export interface FxSnapshot {
  id: number;
  date: string;
  /**
   * Units of each currency per 1 EUR: { USD, GBP, CHF, AED, SGD, HKD }.
   */
  ratesPerEur:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segment-pages".
 */
export interface SegmentPage {
  id: number;
  title: string;
  market: number | Market;
  /**
   * The §5.5 controlled taxonomy — never free text.
   */
  segment:
    | 'waterfront-estates'
    | 'vineyard-estates'
    | 'ski-chalets'
    | 'penthouses'
    | 'private-islands'
    | 'historic-estates'
    | 'equestrian-estates'
    | 'new-developments'
    | 'golf-estates';
  /**
   * Opens with a 40–60-word direct answer (§15.6). Required before the combination goes live.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Question-form entries rendered with FAQPage JSON-LD (§15.5). Answer real buyer questions — tenure, structures, access.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Demo data: SAMPLE notice, noindex, out of sitemaps.
   */
  isSample?: boolean | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agency-applications".
 */
export interface AgencyApplication {
  id: number;
  agencyName: string;
  contactName: string;
  email: string;
  phone?: string | null;
  country?: string | null;
  website?: string | null;
  /**
   * What they would list — markets, count, value range (§8.2).
   */
  inventoryNote?: string | null;
  status: 'new' | 'approved' | 'rejected';
  /**
   * Internal decision note.
   */
  reviewNote?: string | null;
  consentIp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomies".
 */
export interface Taxonomy {
  id: number;
  name: string;
  slug: string;
  group: 'lifestyle' | 'style' | 'collection';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  /**
   * Demo data: SAMPLE notice, noindex, out of sitemaps.
   */
  isSample?: boolean | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: string | null;
  statusCode: '301' | '302' | '410';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action:
    | 'create'
    | 'update'
    | 'delete'
    | 'publish'
    | 'enquiry_view'
    | 'enquiry_anonymized'
    | 'lead_view'
    | 'lead_anonymized'
    | 'status_change';
  targetCollection: string;
  targetId: string;
  summary?: string | null;
  actor?: (number | null) | User;
  actorEmail?: string | null;
  actorRole?: string | null;
  agency?: (number | null) | Agency;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs".
 */
export interface ImportJob {
  id: number;
  agency: number | Agency;
  sourceFilename?: string | null;
  kind?: ('csv' | 'xlsx' | 'feed') | null;
  status: 'queued' | 'dry_run' | 'running' | 'complete' | 'failed';
  rowsProcessed?: number | null;
  rowsFailed?: number | null;
  /**
   * Row-by-row ok/warning/error with the exact reason and column (§8.4).
   */
  errorReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  analytics: boolean;
  marketing: boolean;
  locale?: string | null;
  ipHash?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'agencies';
        value: number | Agency;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'markets';
        value: number | Market;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'saved-listings';
        value: number | SavedListing;
      } | null)
    | ({
        relationTo: 'requirements';
        value: number | Requirement;
      } | null)
    | ({
        relationTo: 'member-activity';
        value: number | MemberActivity;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'fx-snapshots';
        value: number | FxSnapshot;
      } | null)
    | ({
        relationTo: 'segment-pages';
        value: number | SegmentPage;
      } | null)
    | ({
        relationTo: 'agency-applications';
        value: number | AgencyApplication;
      } | null)
    | ({
        relationTo: 'taxonomies';
        value: number | Taxonomy;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'import-jobs';
        value: number | ImportJob;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  agency?: T;
  agentProfile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  country?: T;
  preferredLocale?: T;
  memberType?: T;
  status?: T;
  emailVerifiedAt?: T;
  marketingConsent?: T;
  consentedAt?: T;
  consentIp?: T;
  lastActiveAt?: T;
  source?: T;
  utm?: T;
  twoFactorEnabled?: T;
  totpSecret?: T;
  pendingTotpSecret?: T;
  reserved?:
    | T
    | {
        ndaStatus?: T;
        ndaSignedAt?: T;
        capabilityStatus?: T;
        capabilityBand?: T;
        tier?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  visibility?: T;
  agency?: T;
  credit?: T;
  licence?: T;
  sourceUrl?: T;
  sourceId?: T;
  blurhash?: T;
  dominantColor?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        w320?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w640?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w960?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w1280?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w1920?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w2560?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  documentType?: T;
  property?: T;
  agency?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  reference?: T;
  propertyType?: T;
  availableFrom?: T;
  priceType?: T;
  priceAmount?: T;
  currency?: T;
  priceBandMin?: T;
  priceBandMax?: T;
  internalValueEur?: T;
  tenure?: T;
  ownershipStructure?: T;
  saleStructure?: T;
  annualRunningCostEur?: T;
  taxNotes?: T;
  mandateType?: T;
  commissionTerms?: T;
  bedrooms?: T;
  bathrooms?: T;
  receptionRooms?: T;
  staffAccommodation?: T;
  builtAreaSqm?: T;
  plotAreaSqm?: T;
  plotAreaHa?: T;
  terraceAreaSqm?: T;
  floors?: T;
  yearBuilt?: T;
  renovatedYear?: T;
  parkingSpaces?: T;
  architect?: T;
  heritageStatus?: T;
  condition?: T;
  energyRating?: T;
  provenance?: T;
  features?: T;
  waterfront?:
    | T
    | {
        waterAccess?: T;
        waterBodyType?: T;
        waterFrontageM?: T;
        mooringType?: T;
        maxBoatLoaM?: T;
        berthCount?: T;
      };
  location?:
    | T
    | {
        label?: T;
        addressLine?: T;
        locality?: T;
        province?: T;
        region?: T;
        country?: T;
        continent?: T;
        market?: T;
        coordinates?: T;
        coordinatePrecision?: T;
        publicGeography?: T;
      };
  media?: T;
  videoUrl?: T;
  virtualTourUrl?: T;
  floorplans?: T;
  documents?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  publication?: T;
  channel?: T;
  priceDisclosure?: T;
  valueTier?: T;
  slug?: T;
  agency?: T;
  agent?: T;
  status?: T;
  moderation?: T;
  moderationNote?: T;
  featured?: T;
  isSample?: T;
  priceEur?: T;
  priceBandMinEur?: T;
  priceBandMaxEur?: T;
  publishedAt?: T;
  expiresAt?: T;
  lastVerifiedAt?: T;
  expiryReminderSentAt?: T;
  sourceType?: T;
  duplicateOf?: T;
  fingerprint?: T;
  viewCount?: T;
  memberViewCount?: T;
  enquiryCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies_select".
 */
export interface AgenciesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  country?: T;
  languages?: T;
  website?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  licenceNumber?: T;
  verified?: T;
  verifiedAt?: T;
  tier?: T;
  listingQuota?: T;
  feed?:
    | T
    | {
        feedUrl?: T;
        feedToken?: T;
        feedFormat?: T;
        feedLastRunAt?: T;
        feedLastStatus?: T;
        fieldMapping?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  agency?: T;
  photo?: T;
  role?: T;
  languages?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  receivesLeads?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  region?: T;
  polygon?: T;
  centroid?: T;
  heroImage?: T;
  answer?: T;
  intro?: T;
  buyingNotes?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedMarkets?: T;
  stats?:
    | T
    | {
        medianPriceEurPerSqm?:
          | T
          | {
              value?: T;
              source?: T;
              asOfDate?: T;
            };
        primeEntryEur?:
          | T
          | {
              value?: T;
              source?: T;
              asOfDate?: T;
            };
        yoyChangePct?:
          | T
          | {
              value?: T;
              source?: T;
              asOfDate?: T;
            };
        avgDaysOnMarket?:
          | T
          | {
              value?: T;
              source?: T;
              asOfDate?: T;
            };
        transactionVolumeBand?:
          | T
          | {
              value?: T;
              source?: T;
              asOfDate?: T;
            };
      };
  isSample?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  property?: T;
  agency?: T;
  agent?: T;
  member?: T;
  locale?: T;
  source?: T;
  status?: T;
  consent?:
    | T
    | {
        consentMarketing?: T;
        consentedAt?: T;
        consentIp?: T;
      };
  reminderSentAt?: T;
  utm?: T;
  crmContactId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-listings_select".
 */
export interface SavedListingsSelect<T extends boolean = true> {
  member?: T;
  property?: T;
  note?: T;
  savedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requirements_select".
 */
export interface RequirementsSelect<T extends boolean = true> {
  member?: T;
  budgetMinEur?: T;
  budgetMaxEur?: T;
  currency?: T;
  markets?: T;
  propertyTypes?: T;
  mustHaveFeatures?: T;
  timeline?: T;
  notes?: T;
  status?: T;
  notifyByEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-activity_select".
 */
export interface MemberActivitySelect<T extends boolean = true> {
  member?: T;
  property?: T;
  action?: T;
  at?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  pdf?: T;
  charts?: T;
  publicationDate?: T;
  authors?:
    | T
    | {
        name?: T;
        id?: T;
      };
  markets?: T;
  isSample?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fx-snapshots_select".
 */
export interface FxSnapshotsSelect<T extends boolean = true> {
  date?: T;
  ratesPerEur?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segment-pages_select".
 */
export interface SegmentPagesSelect<T extends boolean = true> {
  title?: T;
  market?: T;
  segment?: T;
  intro?: T;
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  isSample?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agency-applications_select".
 */
export interface AgencyApplicationsSelect<T extends boolean = true> {
  agencyName?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  country?: T;
  website?: T;
  inventoryNote?: T;
  status?: T;
  reviewNote?: T;
  consentIp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomies_select".
 */
export interface TaxonomiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  author?: T;
  publishedAt?: T;
  isSample?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  targetCollection?: T;
  targetId?: T;
  summary?: T;
  actor?: T;
  actorEmail?: T;
  actorRole?: T;
  agency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs_select".
 */
export interface ImportJobsSelect<T extends boolean = true> {
  agency?: T;
  sourceFilename?: T;
  kind?: T;
  status?: T;
  rowsProcessed?: T;
  rowsFailed?: T;
  errorReport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  analytics?: T;
  marketing?: T;
  locale?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}